default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: myuser
  password: mypassword
  host: localhost

development:
  <<: *default
  database: discord_clone_development

test:
  <<: *default
  database: discord_clone_test

production:
  <<: *default
  database: discord_clone_production
  username: discord_clone
  password: <%= ENV['DISCORD_CLONE_DATABASE_PASSWORD'] %>